name: build-sphinx-to-gh-pages

# Declaring environment variables to be used later
env:
  GITHUB_ACTOR: simado
  GITHUB_REPOSITORY: simado/patfu
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

on: 
  # push:
  #   branches: [ main ]
  # Manual
  workflow_dispatch:


jobs:
  build_sphinx_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
      - name: Get prerequisites and clone repository
        run: |
          set -x
          apt-get update
          apt-get install -y git
          git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        shell: bash

      - name: Run build script for Sphinx pages
        run: |
          chmod +x ./scripts/buildsite.sh
          ./scripts/buildsite.sh
        shell: bash